<a href="https://colab.research.google.com/github/SURESHASWATHI/assignment/blob/main/python_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task
Generate Python code and explanations for the provided list of exercises covering data structures, control structures, Numpy, and Pandas.

## Data structures & control structures

### Subtask:
Generate code and explanations for the operations requested on lists, tuples, sets, and dictionaries, and for the control structure exercises (voting eligibility, grading, number check).


**Reasoning**:
The subtask requires generating code for data structures and control structures. I will start by creating code for list operations, then move on to tuples, sets, and dictionaries, and finally address the control structure exercises. I will include comments and print statements as requested.



In [1]:
# List Operations
# Initialize a list
my_list = [1, 2, 3, 4, 5]
print(f"Initial list: {my_list}")

# Add an element to the end of the list
my_list.append(6)
print(f"After appending 6: {my_list}")

# Add elements from another list
my_list.extend([7, 8])
print(f"After extending with [7, 8]: {my_list}")

# Insert an element at a specific index
my_list.insert(0, 0)
print(f"After inserting 0 at index 0: {my_list}")

# Remove the first occurrence of a value
my_list.remove(4)
print(f"After removing 4: {my_list}")

# Remove an element at a specific index
popped_element = my_list.pop(0)
print(f"After popping element at index 0: {my_list}")
print(f"Popped element: {popped_element}")

# Access elements by index
print(f"Element at index 2: {my_list[2]}")

# Slice the list
print(f"Slice from index 1 to 4: {my_list[1:5]}")

# Check membership
print(f"Is 3 in the list? {3 in my_list}")
print(f"Is 10 in the list? {10 in my_list}")

# Length of the list
print(f"Length of the list: {len(my_list)}")

# Tuple Operations
# Initialize a tuple
my_tuple = (10, 20, 30, 40, 50)
print(f"\nInitial tuple: {my_tuple}")

# Access elements by index
print(f"Element at index 1: {my_tuple[1]}")

# Slice the tuple
print(f"Slice from index 2 to 4: {my_tuple[2:5]}")

# Check membership
print(f"Is 30 in the tuple? {30 in my_tuple}")
print(f"Is 60 in the tuple? {60 in my_tuple}")

# Length of the tuple
print(f"Length of the tuple: {len(my_tuple)}")

# Note: Tuples are immutable, so operations like adding, removing, or modifying elements are not possible.

# Set Operations
# Initialize a set
my_set = {1, 2, 3, 4, 5}
print(f"\nInitial set: {my_set}")

# Add an element to the set
my_set.add(6)
print(f"After adding 6: {my_set}")

# Add multiple elements from an iterable
my_set.update([7, 8])
print(f"After updating with [7, 8]: {my_set}")

# Remove an element from the set (raises error if element not found)
my_set.remove(3)
print(f"After removing 3: {my_set}")

# Remove an element if it is present
my_set.discard(10) # Does not raise an error if 10 is not in the set
print(f"After discarding 10: {my_set}")

# Check membership
print(f"Is 4 in the set? {4 in my_set}")
print(f"Is 10 in the set? {10 in my_set}")

# Length of the set
print(f"Length of the set: {len(my_set)}")

# Dictionary Operations
# Initialize a dictionary
my_dict = {'a': 1, 'b': 2, 'c': 3}
print(f"\nInitial dictionary: {my_dict}")

# Access value by key
print(f"Value for key 'b': {my_dict['b']}")

# Add or update a key-value pair
my_dict['d'] = 4
print(f"After adding key 'd': {my_dict}")

my_dict['a'] = 10
print(f"After updating value for key 'a': {my_dict}")

# Remove a key-value pair
del my_dict['c']
print(f"After deleting key 'c': {my_dict}")

# Get keys, values, and items
print(f"Keys: {my_dict.keys()}")
print(f"Values: {my_dict.values()}")
print(f"Items: {my_dict.items()}")

# Check membership (checks for keys)
print(f"Is 'b' in the dictionary? {'b' in my_dict}")
print(f"Is 'e' in the dictionary? {'e' in my_dict}")

# Length of the dictionary
print(f"Length of the dictionary: {len(my_dict)}")

# Control Structure Exercises

# Voting Eligibility
def check_voting_eligibility(age):
  """Checks if a person is eligible to vote based on age."""
  if age >= 18:
    print(f"With age {age}, the person is eligible to vote.")
  else:
    print(f"With age {age}, the person is not eligible to vote.")

check_voting_eligibility(20)
check_voting_eligibility(16)

# Grading
def assign_grade(score):
  """Assigns a letter grade based on a numerical score."""
  if score >= 90:
    print(f"With score {score}, the grade is A.")
  elif score >= 80:
    print(f"With score {score}, the grade is B.")
  elif score >= 70:
    print(f"With score {score}, the grade is C.")
  elif score >= 60:
    print(f"With score {score}, the grade is D.")
  else:
    print(f"With score {score}, the grade is F.")

assign_grade(95)
assign_grade(82)
assign_grade(75)
assign_grade(63)
assign_grade(55)

# Number Check
def check_number(number):
  """Checks if a number is positive, negative, or zero."""
  if number > 0:
    print(f"The number {number} is positive.")
  elif number < 0:
    print(f"The number {number} is negative.")
  else:
    print(f"The number {number} is zero.")

check_number(10)
check_number(-5)
check_number(0)

Initial list: [1, 2, 3, 4, 5]
After appending 6: [1, 2, 3, 4, 5, 6]
After extending with [7, 8]: [1, 2, 3, 4, 5, 6, 7, 8]
After inserting 0 at index 0: [0, 1, 2, 3, 4, 5, 6, 7, 8]
After removing 4: [0, 1, 2, 3, 5, 6, 7, 8]
After popping element at index 0: [1, 2, 3, 5, 6, 7, 8]
Popped element: 0
Element at index 2: 3
Slice from index 1 to 4: [2, 3, 5, 6]
Is 3 in the list? True
Is 10 in the list? False
Length of the list: 7

Initial tuple: (10, 20, 30, 40, 50)
Element at index 1: 20
Slice from index 2 to 4: (30, 40, 50)
Is 30 in the tuple? True
Is 60 in the tuple? False
Length of the tuple: 5

Initial set: {1, 2, 3, 4, 5}
After adding 6: {1, 2, 3, 4, 5, 6}
After updating with [7, 8]: {1, 2, 3, 4, 5, 6, 7, 8}
After removing 3: {1, 2, 4, 5, 6, 7, 8}
After discarding 10: {1, 2, 4, 5, 6, 7, 8}
Is 4 in the set? True
Is 10 in the set? False
Length of the set: 7

Initial dictionary: {'a': 1, 'b': 2, 'c': 3}
Value for key 'b': 2
After adding key 'd': {'a': 1, 'b': 2, 'c': 3, 'd': 4}
After updat

## Numpy

### Subtask:
Generate code to create the specified Numpy arrays and generate a random 4x4 array.


**Reasoning**:
Import the numpy library and create the specified numpy arrays, including a random 4x4 array, then print them.



In [2]:
import numpy as np

# Create a 1D Numpy array containing the numbers from 0 to 9.
array_1d = np.arange(10)
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)
print("-" * 20)

# Create a 2D Numpy array of shape (3, 3) filled with zeros.
array_2d_zeros = np.zeros((3, 3))
print("2D Array (Zeros):")
print(array_2d_zeros)
print("Shape:", array_2d_zeros.shape)
print("-" * 20)

# Create a 3D Numpy array of shape (2, 3, 4) filled with ones.
array_3d_ones = np.ones((2, 3, 4))
print("3D Array (Ones):")
print(array_3d_ones)
print("Shape:", array_3d_ones.shape)
print("-" * 20)

# Create a 1D Numpy array with 5 elements, where the values range from 10 to 50, spaced evenly.
array_1d_linspace = np.linspace(10, 50, 5)
print("1D Array (Linspace):")
print(array_1d_linspace)
print("Shape:", array_1d_linspace.shape)
print("-" * 20)

# Generate a random 4x4 Numpy array with values between 0 and 1.
random_array_4x4 = np.random.rand(4, 4)
print("Random 4x4 Array:")
print(random_array_4x4)
print("Shape:", random_array_4x4.shape)
print("-" * 20)

1D Array:
[0 1 2 3 4 5 6 7 8 9]
Shape: (10,)
--------------------
2D Array (Zeros):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (3, 3)
--------------------
3D Array (Ones):
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Shape: (2, 3, 4)
--------------------
1D Array (Linspace):
[10. 20. 30. 40. 50.]
Shape: (5,)
--------------------
Random 4x4 Array:
[[0.76078295 0.25970062 0.03282154 0.69739092]
 [0.68293845 0.94684348 0.75456949 0.9888852 ]
 [0.37346647 0.75296012 0.75374727 0.62973292]
 [0.40960627 0.94765717 0.50799118 0.40318686]]
Shape: (4, 4)
--------------------


## Pandas

### Subtask:
Generate code to create a DataFrame from a Numpy array and perform the specified operations on a manually created DataFrame.


**Reasoning**:
Generate the Python code to create a DataFrame from a Numpy array and perform the specified operations on a manually created DataFrame according to the instructions.



In [3]:
import numpy as np
import pandas as pd

# 1. Create a Numpy array with shape (5, 3) containing random integers between 0 and 100.
numpy_array = np.random.randint(0, 101, size=(5, 3))
print("Numpy Array:")
print(numpy_array)

# 2. Create a Pandas DataFrame from this Numpy array. Assign column names 'A', 'B', and 'C'.
df_from_numpy = pd.DataFrame(numpy_array, columns=['A', 'B', 'C'])
print("\nDataFrame from Numpy Array:")
display(df_from_numpy)

# 3. Create a dictionary representing data for a different DataFrame with keys 'Name', 'Age', and 'City', and corresponding lists of data.
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 35, 30, 40, 22],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney']
}

# 4. Create a Pandas DataFrame from this dictionary.
df_from_dict = pd.DataFrame(data)
print("\nDataFrame from Dictionary:")
display(df_from_dict)

# 5. Select and print the 'Name' column from the dictionary-created DataFrame.
print("\n'Name' column:")
print(df_from_dict['Name'])

# 6. Select and print the first two rows of the dictionary-created DataFrame.
print("\nFirst two rows:")
display(df_from_dict.head(2))

# 7. Select and print rows from the dictionary-created DataFrame where 'Age' is greater than 30.
print("\nRows where Age > 30:")
display(df_from_dict[df_from_dict['Age'] > 30])

# 8. Add a new column named 'Salary' to the dictionary-created DataFrame with a list of numerical values.
df_from_dict['Salary'] = [50000, 60000, 55000, 70000, 48000]
print("\nDataFrame after adding 'Salary' column:")
display(df_from_dict)

# 9. Drop the 'City' column from the dictionary-created DataFrame.
df_from_dict = df_from_dict.drop('City', axis=1)
print("\nDataFrame after dropping 'City' column:")
display(df_from_dict)

# 10. Print the final state of the dictionary-created DataFrame after the operations.
print("\nFinal state of the dictionary-created DataFrame:")
display(df_from_dict)

Numpy Array:
[[63 61  8]
 [40 51 75]
 [ 9 86 89]
 [11 83 88]
 [62 42 25]]

DataFrame from Numpy Array:


A   B   C
0  63  61   8
1  40  51  75
2   9  86  89
3  11  83  88
4  62  42  25


DataFrame from Dictionary:


Name  Age      City
0    Alice   25  New York
1      Bob   35    London
2  Charlie   30     Paris
3    David   40     Tokyo
4      Eve   22    Sydney


'Name' column:
0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object

First two rows:


Name  Age      City
0  Alice   25  New York
1    Bob   35    London


Rows where Age > 30:


Name  Age    City
1    Bob   35  London
3  David   40   Tokyo


DataFrame after adding 'Salary' column:


Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   35    London   60000
2  Charlie   30     Paris   55000
3    David   40     Tokyo   70000
4      Eve   22    Sydney   48000


DataFrame after dropping 'City' column:


Name  Age  Salary
0    Alice   25   50000
1      Bob   35   60000
2  Charlie   30   55000
3    David   40   70000
4      Eve   22   48000


Final state of the dictionary-created DataFrame:


Name  Age  Salary
0    Alice   25   50000
1      Bob   35   60000
2  Charlie   30   55000
3    David   40   70000
4      Eve   22   48000

## Summary:

### Data Analysis Key Findings

*   Python code was successfully generated to demonstrate operations on fundamental data structures: lists, tuples, sets, and dictionaries, including adding, removing, accessing, and checking membership.
*   Control structures were demonstrated through functions for checking voting eligibility, assigning grades based on scores, and classifying numbers as positive, negative, or zero.
*   NumPy arrays of various dimensions (1D, 2D, 3D) were created using functions like `arange`, `zeros`, `ones`, and `linspace`.
*   A random 4x4 NumPy array was successfully generated using `np.random.rand`.
*   A Pandas DataFrame was successfully created from a NumPy array and assigned column names.
*   A Pandas DataFrame was created from a Python dictionary, and operations like column selection, row slicing, conditional row selection, column addition, and column dropping were demonstrated.

### Insights or Next Steps

*   The code provides a solid foundation for understanding basic Python data structures, control flow, and the core functionalities of NumPy and Pandas for data manipulation.
*   Future tasks could involve more complex operations like data cleaning, aggregation, merging DataFrames, or performing statistical analysis using these libraries.
